//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CameraClient.CameraServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CameraServiceReference.ICameraService")]
    public interface ICameraService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICameraService/SetupCamera", ReplyAction="http://tempuri.org/ICameraService/SetupCameraResponse")]
        void SetupCamera(RaspicamServer.RaspicamParameters parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICameraService/SetupCamera", ReplyAction="http://tempuri.org/ICameraService/SetupCameraResponse")]
        System.Threading.Tasks.Task SetupCameraAsync(RaspicamServer.RaspicamParameters parameters);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICameraService/CaptureImage", ReplyAction="http://tempuri.org/ICameraService/CaptureImageResponse")]
        byte[] CaptureImage();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICameraService/CaptureImage", ReplyAction="http://tempuri.org/ICameraService/CaptureImageResponse")]
        System.Threading.Tasks.Task<byte[]> CaptureImageAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICameraServiceChannel : CameraClient.CameraServiceReference.ICameraService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CameraServiceClient : System.ServiceModel.ClientBase<CameraClient.CameraServiceReference.ICameraService>, CameraClient.CameraServiceReference.ICameraService {
        
        public CameraServiceClient() {
        }
        
        public CameraServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CameraServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CameraServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CameraServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SetupCamera(RaspicamServer.RaspicamParameters parameters) {
            base.Channel.SetupCamera(parameters);
        }
        
        public System.Threading.Tasks.Task SetupCameraAsync(RaspicamServer.RaspicamParameters parameters) {
            return base.Channel.SetupCameraAsync(parameters);
        }
        
        public byte[] CaptureImage() {
            return base.Channel.CaptureImage();
        }
        
        public System.Threading.Tasks.Task<byte[]> CaptureImageAsync() {
            return base.Channel.CaptureImageAsync();
        }
    }
}
